// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VsixTools2022
{
    internal sealed partial class Vsix
    {
        public const string Id = "VsixTools2022.06c686f8-467f-4824-9d13-4ccc5b2fd749";
        public const string Name = "MRLacey Tools for VS2022";
        public const string Description = @"A collection of Visual Studio 2022 extensions created by Matt Lacey.";
        public const string Language = "en-US";
        public const string Version = "1.26";
        public const string Author = "Matt Lacey";
        public const string Tags = "";
    }
}
